Lesson 2. Hometask by Anna K
ChangeRequest/introduction.hw1 pull request #16
Opened 2017-06-29 12:13 UTC by AnnaKlueva

2017-06-29 13:51 UTC, didva requested changes

2017-06-29 13:51 UTC, didva commented on src/main/java/school/lemon/changerequest/java/introduction/hw1/Task10.java
> +       return new Integer(n).toString().contains("2");
It's a shortest, but not the fastest way to solve this task. Please try to do it without `toString`.

2017-06-29 13:51 UTC, didva commented on src/main/java/school/lemon/changerequest/java/introduction/hw1/Task4.java
> +        Double[] array = {a,b,c};
Overcomplicated. You have only 3 numbers, there is no need to implement sorting.

2017-06-29 13:51 UTC, didva commented on src/main/java/school/lemon/changerequest/java/introduction/hw1/Task5.java
> +        return (2*Math.sin(x-Math.PI/6)*calculateB(z))/(0.5+Math.pow(Math.sin(y),2));
This is extremely hard to read and understand. Please split it somehow.

2017-06-29 13:51 UTC, didva commented on src/main/java/school/lemon/changerequest/java/introduction/hw1/Task5.java
> +        return 1+Math.pow(z,2)/(3+Math.pow(z,2)/5);
Pow is very hard operation so please move out reusable part.

2017-06-29 13:51 UTC, didva commented on src/main/java/school/lemon/changerequest/java/introduction/hw1/Task6.java
> +        return (1+x+Math.pow(x,2)/2+Math.pow(x,3)/6+Math.pow(x,4)/24);
What about more flexible solution?

2017-06-29 13:51 UTC, didva commented on src/main/java/school/lemon/changerequest/java/introduction/hw1/Task8.java
> +            sum = result + (Math.pow((N + i), 2));
```sum += (Math.pow((N + i), 2));```

2017-06-29 13:51 UTC, didva commented on src/main/java/school/lemon/changerequest/java/introduction/hw1/Task9.java
> +                else{
Formatting.

2017-06-29 13:51 UTC, didva commented on src/main/java/school/lemon/changerequest/java/introduction/hw1/Task9.java
> +    private static boolean verifyIsPowerOfThree(int n) {
It's hard to read.
I'd prefer smth like:
```
if (n==) {
return false;
}
...
```

2017-06-29 13:51 UTC, didva commented on src/main/java/school/lemon/changerequest/java/introduction/hw1/Task9.java
> +    private static boolean verifyIsPowerOfThree(int n) {
What about -3, -9 etc?

2017-06-29 14:59 UTC, AnnaKlueva commented on src/main/java/school/lemon/changerequest/java/introduction/hw1/Task6.java
> +        return (1+x+Math.pow(x,2)/2+Math.pow(x,3)/6+Math.pow(x,4)/24);
What do you mean under "flexible"?

2017-06-29 15:02 UTC, AnnaKlueva commented on src/main/java/school/lemon/changerequest/java/introduction/hw1/Task8.java
> +            sum = result + (Math.pow((N + i), 2));
Fixed

2017-06-29 15:09 UTC, AnnaKlueva commented on src/main/java/school/lemon/changerequest/java/introduction/hw1/Task5.java
> +        return 1+Math.pow(z,2)/(3+Math.pow(z,2)/5);
Done

2017-06-29 15:09 UTC, AnnaKlueva commented on src/main/java/school/lemon/changerequest/java/introduction/hw1/Task5.java
> +        return (2*Math.sin(x-Math.PI/6)*calculateB(z))/(0.5+Math.pow(Math.sin(y),2));
Done? but should be reviewed one more time

2017-06-29 15:11 UTC, AnnaKlueva commented on src/main/java/school/lemon/changerequest/java/introduction/hw1/Task9.java
> +                else{
Done

2017-06-29 15:38 UTC, AnnaKlueva commented on src/main/java/school/lemon/changerequest/java/introduction/hw1/Task4.java
> +        Double[] array = {a,b,c};
Done

2017-06-29 15:38 UTC, AnnaKlueva commented on src/main/java/school/lemon/changerequest/java/introduction/hw1/Task9.java
> +    private static boolean verifyIsPowerOfThree(int n) {
Done

2017-06-29 15:39 UTC, AnnaKlueva commented on src/main/java/school/lemon/changerequest/java/introduction/hw1/Task9.java
> +    private static boolean verifyIsPowerOfThree(int n) {
Updated

2017-06-30 08:44 UTC, AnnaKlueva commented on src/main/java/school/lemon/changerequest/java/introduction/hw1/Task10.java
> +       return new Integer(n).toString().contains("2");
Done

2017-06-30 09:33 UTC, didva requested changes

2017-06-30 09:33 UTC, didva commented on src/main/java/school/lemon/changerequest/java/introduction/hw1/Task10.java
> +        else{
1) Formatting
2) No need in `else` at all

2017-06-30 09:33 UTC, didva commented on src/main/java/school/lemon/changerequest/java/introduction/hw1/Task4.java
> +        double[] array = {a, b, c};
It's better but, still overcomplicated for 3 elements.

2017-06-30 09:33 UTC, didva commented on src/main/java/school/lemon/changerequest/java/introduction/hw1/Task6.java
> +        return (1+x+Math.pow(x,2)/2+Math.pow(x,3)/6+Math.pow(x,4)/24);
Let's say you wanna do the same calculations but 10 times instead of 4. Are you still going to copy-paste?

2017-06-30 09:33 UTC, didva commented on src/main/java/school/lemon/changerequest/java/introduction/hw1/Task9.java
> +        if (n == 0) {
I'd prefer smth like:
```
if (n == 1) {
  return true;
}
if (n < 3) {
  return false;
}
return verifyIsPowerOfThree(n / 3);
```

2017-06-30 09:33 UTC, didva commented on src/main/java/school/lemon/changerequest/java/introduction/hw1/Task9.java
> +        if (n == 0) {
By the way, you are doing such things via recursion. 
Have you tried to do it via loop? I'd prefer loops, but no need to change.

2017-07-03 14:25 UTC, AnnaKlueva commented on src/main/java/school/lemon/changerequest/java/introduction/hw1/Task10.java
> +        else{
Ok, deleted

2017-07-03 14:29 UTC, AnnaKlueva commented on src/main/java/school/lemon/changerequest/java/introduction/hw1/Task6.java
> +        return (1+x+Math.pow(x,2)/2+Math.pow(x,3)/6+Math.pow(x,4)/24);
Are you talking about recursion?

2017-07-04 10:21 UTC, didva requested changes

2017-07-04 10:21 UTC, didva commented on src/main/java/school/lemon/changerequest/java/introduction/hw1/Task6.java
> +        for (int i=0; i<=4;i++){
You can avoid `Math.pow` and `factorial` functions.

2017-09-05 08:06 UTC, didva commented
Done with comments.

2017-09-05 08:06 UTC, closed without merging